version: '3'
services:
  frp_server:
    image: geektr/frp
    environment:
      - FRP_SERVER_ADDR=your_server_address
      - FRP_PRIVILEGE_TOKEN=your_serect_frp_privilege_token
      - FRP_DASHBOARD_PWD=your_frp_dashboard_password
    restart: always
    network_mode: "host"
    volumes:
      - ./frps.ini:/etc/frp/frps.ini:ro
